package ru.repethelper.domain;

public enum EmailNotificationType {
    CONNECTION_REQUEST_RECEIVED,
    CONNECTION_ACCEPTED,
    CONNECTION_REJECTED,
    LESSON_CREATED,
    LESSON_RESCHEDULED,
    LESSON_DELETED,
    LESSON_SERIES_CREATED,
    LESSON_SERIES_RESCHEDULED,
    LESSON_SERIES_DELETED,
    HOMEWORK_UPDATED,
    LESSON_REMINDER,
    SUBSCRIPTION_CREATED
}
